"""Cross-scenario uniqueness.

These would not be caught by any single-scenario test: every entity from every
scenario lands in one set of tables, so ids must be unique across the whole corpus,
not merely within a case. The bug that motivated this file only appeared at ~96
scenarios, and the scenario_id collision would have silently merged a training
scenario with a test one.
"""

import pytest

from scenarios.generator.catalog import BUILDERS
from scenarios.generator.run import SPLIT_RANGES, build

CODES = sorted(BUILDERS)

ID_FIELDS = [
    ("customers", "customer_id"), ("verifications", "verification_id"),
    ("accounts", "account_id"), ("entries", "entry_id"), ("cards", "card_id"),
    ("authorizations", "auth_id"), ("settlements", "settlement_id"),
    ("alerts", "alert_id"), ("deliveries", "delivery_id"),
    ("events", "event_id"), ("cases", "case_id"),
]


def _corpus(per_class: int = 4):
    """A realistic multi-split corpus, mirroring how run.py allocates seeds."""
    worlds, manifests = [], []
    for split, (lo, _) in SPLIT_RANGES.items():
        for idx, code in enumerate(CODES):
            for i in range(per_class):
                w, m = build(code, lo + i * 1000 + idx)
                worlds.append(w)
                manifests.append(m)
    return worlds, manifests


def test_scenario_ids_unique_across_all_splits():
    _, manifests = _corpus()
    ids = [m["scenario_id"] for m in manifests]
    dupes = {i for i in ids if ids.count(i) > 1}
    assert not dupes, f"scenario_id collisions across splits: {sorted(dupes)[:5]}"


def test_scenario_id_encodes_its_split():
    """A test scenario and a train scenario must never share an id, or the
    split boundary the seed ranges enforce is meaningless."""
    _, manifests = _corpus(per_class=2)
    by_id = {}
    for m in manifests:
        assert by_id.setdefault(m["scenario_id"], m["split"]) == m["split"]


@pytest.mark.parametrize("field", [f for _, f in ID_FIELDS])
def test_entity_ids_unique_across_corpus(field):
    worlds, _ = _corpus()
    attr = next(a for a, f in ID_FIELDS if f == field)
    seen: dict[str, str] = {}
    for w in worlds:
        for row in getattr(w, attr):
            key = row[field]
            prev = seen.get(key)
            assert prev is None, (
                f"{field} {key!r} generated by both {prev} and {w.scenario_id} — "
                "entity ids share one table space and must be globally unique"
            )
            seen[key] = w.scenario_id


def test_provider_refs_unique_across_corpus():
    """provider_event_id drives webhook lookups; a collision would make one
    scenario's evidence appear inside another's investigation."""
    worlds, _ = _corpus()
    seen: dict[str, str] = {}
    for w in worlds:
        for attr in ("verifications", "cards", "authorizations", "settlements"):
            for row in getattr(w, attr):
                ref = row.get("provider_ref")
                if ref is None:
                    continue
                prev = seen.get(ref)
                assert prev is None, f"provider_ref {ref!r} shared by {prev} and {w.scenario_id}"
                seen[ref] = w.scenario_id
